working_dir: '/data/swamyvs/ocular_transcriptomes_paper/'
data_dir: '/data/swamyvs/ocular_transcriptomes_pipeline/'
sample_file: '/data/swamyvs/ocular_transcriptomes_pipeline/sampleTableFull.tsv'
salmon_version: 'salmon/0.14.1'
R_version: 'R/3.5.0'
bedtools_version: 'bedtools/2.27.1'
fastq_path: '/data/OGVFB_BG/EiaD_2019_05/'
TransDecoder_version: 'TransDecoder/5.0.1'
